### ISSUE TITLE
easyer

### ISSUE THREAD

**Issue by MateiGamingYTB** [Zadezter/MineFriends#3]
add direct command /accept not /frends accept, its easyer for noobs

**Comment by Zadezter** [comment]
Nope. I couldn't add a /accept without friend. I only do /friend accept.
Second, "easyer" is for your noob word. It should be "easier".

**Comment by MateiGamingYTB** [comment]
..........

**Comment by MateiGamingYTB** [comment]
i m not good at english idiot....
